<a href="https://colab.research.google.com/github/Nish613/OlympicMedals_MLPrediction/blob/ML-model/OlympicMedals_MLPrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
teams = pd.read_csv("teams.csv")
teams.head()

,team,country,year,events,athletes,age,height,weight,medals,prev_medals,prev_3_medals
0,AFG,Afghanistan,1964,8,8,22.0,161.0,64.2,0,0.0,0.0
1,AFG,Afghanistan,1968,5,5,23.2,170.2,70.0,0,0.0,0.0
2,AFG,Afghanistan,1972,8,8,29.0,168.3,63.8,0,0.0,0.0
3,AFG,Afghanistan,1980,11,11,23.6,168.4,63.2,0,0.0,0.0
4,AFG,Afghanistan,2004,5,5,18.6,170.8,64.8,0,0.0,0.0

In [ ]:
teams = teams[["team","country","year","athletes","age","prev_medals","medals"]]
teams.head()

  team      country  year  athletes   age  prev_medals  medals
0  AFG  Afghanistan  1964         8  22.0          0.0       0
1  AFG  Afghanistan  1968         5  23.2          0.0       0
2  AFG  Afghanistan  1972         8  29.0          0.0       0
3  AFG  Afghanistan  1980        11  23.6          0.0       0
4  AFG  Afghanistan  2004         5  18.6          0.0       0